apiVersion: v1
kind: ConfigMap
metadata:
  name: warm-up-bot-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: esquenta_chips
  DB_USER: root
  PORT: "3001"
  NODE_ENV: production
  WEBHOOK_URL: http://localhost:3001/api/webhooks
