apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warm-up-bot-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - meu-dominio.com # será substituído dinamicamente
      secretName: warm-up-bot-tls
  rules:
    - host: meu-dominio.com # será substituído dinamicamente
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: warm-up-bot
                port:
                  number: 80
