apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: warm-up-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jhowbhz/warm-up-bot.git
    targetRevision: stable
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: warm-up-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
