apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: warm-up-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jhowbhz/warm-up-bot.git
    targetRevision: stable
    path: k8s/helm # Agora aponta para a pasta do Helm Chart
    helm:
      parameters:
        - name: ingress.host
          value: meu-dominio.com # VocÃª vai poder editar isso direto na UI do ArgoCD!
  destination:
    server: https://kubernetes.default.svc
    namespace: warm-up-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
